# Generated by Django 2.2.28 on 2023-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230518_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test2',
        ),
        migrations.AddField(
            model_name='user',
            name='testdaniel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
